# Generated by Django 4.0.5 on 2022-07-21 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='education',
            name='graduation_date',
        ),
        migrations.RemoveField(
            model_name='education',
            name='graduation_type',
        ),
        migrations.RemoveField(
            model_name='education',
            name='thesis',
        ),
    ]
