# Generated by Django 4.0.5 on 2022-07-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_remove_education_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='admission_date',
        ),
        migrations.AddField(
            model_name='familymember',
            name='title',
            field=models.CharField(default='You', max_length=100),
            preserve_default=False,
        ),
    ]
