# Generated by Django 4.0.5 on 2022-07-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_remove_education_admission_date_familymember_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='thesis',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
